version: '2'
services:
  db:
    build: 
      context: ../../
      dockerfile: make/dev/container/db/Dockerfile
    image: dev_db:dev
    restart: always
    volumes:
      - /data/board/database:/var/lib/mysql
      - ../config/db/my.cnf:/etc/mysql/conf.d/my.cnf
    env_file:
      - ../config/db/env
    networks:
      - dvserver_net
    ports:
      - 3306:3306
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    logging:
      driver: "syslog"
      options:  
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "db"
networks:
  dvserver_net:
    external:
      name: dev_board
