version: '2'
services:
  adminserver:
    build:
      context: ../../
      dockerfile: make/dev/container/adminserver/Dockerfile
    image: dev_adminserver:dev
    restart: always
    volumes:
      - ../:/go/cfgfile
      - /data/board/secrets:/go/secrets
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /data/board/database:/data/board/database
      - /data/board/ansible_k8s:/data/board/ansible_k8s
      - /data/board/make/config:/data/board/make/config
    env_file:
      - ../templates/adminserver/env-dev
    networks:
      - board
    ports:
      - 8081:8080
  proxy-adminserver:
    build:
      context: ../../
      dockerfile: make/dev/container/proxy-adminserver/Dockerfile
    image: dev_adminserver_proxy:dev
    depends_on: 
      - adminserver
    restart: always
    ports:
      - 8082:80
    links:
      - adminserver
    volumes:
      - ../templates/proxy-adminserver/nginx.conf:/etc/nginx/nginx.conf:z
      - ../../src/ui-adminserver/dist:/usr/share/nginx/html:z
    networks:
      - board
networks:
  board:
    external: false
