version: '2'
services:
  log:
    build:
      context: ../../
      dockerfile: make/dev/container/log/Dockerfile
    image: dev_log:dev
    restart: always
    volumes:
      - /var/log/board/:/var/log/docker/
    networks:
      - board
    ports:
      - 1514:514
  mysql:
    build: 
      context: ../../
      dockerfile: make/dev/container/db/Dockerfile
    image: dev_mysql:dev
    restart: always
    volumes:
      - /data/board/database:/var/lib/mysql
    env_file:
      - ../config/db/env
    networks:
      - board
    ports:
      - 3306:3306
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:  
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "mysql"
  gitserver:
    build:
      context: ../../
      dockerfile: make/dev/container/gitserver/Dockerfile
    image: dev_gitserver:dev
    restart: always
    volumes:
      - /data/board/gitserver/repos:/gitserver/repos
      - ../config/ssh_keys:/gitserver/keys
    networks:
      - board
    links:
      - jenkins
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "gitserver"
  jenkins:
    build:
      context: ../../
      dockerfile: make/dev/container/jenkins/Dockerfile
    image: dev_jenkins:dev
    restart: always
    networks:
      - board
    volumes:
      - /data/board/jenkins_home:/var/jenkins_home
      - ../config/ssh_keys:/root/.ssh
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    env_file:
      - ../config/jenkins/env
    ports:
      - 8888:8080
      - 50000:50000
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "jenkins"
  apiserver:
    build:
      context: ../../
      dockerfile: make/dev/container/apiserver/Dockerfile
    image: dev_apiserver:dev
    restart: always
    volumes:
      - ../config/apiserver/app.conf:/go/bin/app.conf:z
      - ../../tools/swagger/vendors/swagger-ui-2.1.4/dist:/go/bin/swagger:z
      - ../config/ssh_keys:/root/.ssh
      - /data/board/gitserver/repos:/repos
    env_file:
      - ../config/apiserver/env
    networks:
      - board
    links:
      - mysql
      - gitserver
    ports: 
      - 8088:8088
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "apiserver"
  tokenserver:
    build:
      context: ../../
      dockerfile: make/dev/container/tokenserver/Dockerfile
    image: dev_tokenserver:dev
    env_file:
      - ../config/tokenserver/env
    restart: always
    volumes:
      - ../config/tokenserver/app.conf:/go/bin/app.conf:z
    networks:
      - board
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "tokenserver"
  collector:
    build:
      context: ../../
      dockerfile: make/dev/container/collector/Dockerfile
    image: dev_collector:dev
    restart: always
    env_file:
      - ../config/collector/env
    networks:
      - board
    links:
      - mysql
    depends_on:
      - log
      - mysql
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "collector" 
  proxy:
    build:
      context: ../../
      dockerfile: make/dev/container/proxy/Dockerfile
    image: dev_proxy:dev
    networks:
      - board
    restart: always
    volumes:
      - ../config/proxy/nginx.conf:/etc/nginx/nginx.conf:z
      - ../../src/ui/dist:/usr/share/nginx/html:z
    ports: 
      - 80:80
    links:
      - apiserver
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "proxy"
  grafana:
    build:
      context: ../../
      dockerfile: make/dev/container/grafana/Dockerfile
    image: dev_grafana:dev
    restart: always
    volumes:
      - /data/board/grafana/lib:/var/lib/grafana
      - /data/board/grafana/log:/var/log/grafana
    env_file:
      - ../config/grafana/env
    networks:
      - board
    ports:
      - 3000:3000
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "grafana"
  graphite:
    build:
      context: ../../
      dockerfile: make/dev/container/graphite/Dockerfile
    image: dev_graphite:dev
    restart: always
    networks:
      - board
    ports:
      - 38080:80
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - 8126:8126
    depends_on:
      - log
    volumes:
      - /opt/graphite/conf
      - /data/board/graphite/storage:/opt/graphite/storage
      - /etc/nginx
      - /opt/statsd
      - /etc/logrotate.d
      - /var/log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "graphite"
networks:
  board:
    external: false
