version: '2'
services:
  uibuilder7.4:
    build:
      context: ../../
      dockerfile: make/dev/container/uibuilder/Dockerfile.arm64v8
    image: inspursoft/uibuilder-arm64v8:7.4
    volumes:
      - ../../src/ui:/board_src
    environment:
      MODE: build
    entrypoint:
      - /entrypoint.sh
  uibuilder-adminserver7.4:
    build:
      context: ../../
      dockerfile: make/dev/container/uibuilder/Dockerfile.arm64v8
    image: inspursoft/uibuilder-arm64v8:7.4
    volumes:
      - ../../src/ui-adminserver:/board_src
    environment:
      MODE: build
    entrypoint:
      - /entrypoint.sh
