version: '2'
services:
  log:
    build:
      context: ./container/log/
      dockerfile: Dockerfile
    restart: always
    volumes:
      - /var/log/board/:/var/log/docker/
    networks:
      - board
    ports:
      - 1514:514
  mysql:
    build: 
      context: ./container/db/
      dockerfile: Dockerfile
    restart: always
    volumes:
      - /data/board/database:/var/lib/mysql
    env_file:
      - ../config/db/env
    networks:
      - board
    ports:
      - 3306:3306
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:  
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "mysql"
  apiserver:
    build:
      context: ../../
      dockerfile: make/dev/container/apiserver/Dockerfile
    restart: always
    volumes:
      - ../../tools/swagger/vendors/swagger-ui-2.1.4/dist:/go/bin/swagger:z
    env_file:
      - ../config/apiserver/env
    networks:
      - board
    links:
      - mysql
    ports: 
      - 8080:8080
    depends_on:
      - log
      - mysql
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "apiserver"
  tokenserver:
    build:
      context: ../../
      dockerfile: make/dev/container/tokenserver/Dockerfile
    env_file:
      - container/tokenserver/env
    restart: always
    networks:
      - board
    ports:
      - 4000:4000
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "tokenserver"
  proxy:
    image: nginx:1.11.5
    networks:
      - board
    restart: always
    volumes:
      - ../config/nginx/nginx.conf:/etc/nginx/nginx.conf:z
      - ../../src/ui/dist:/usr/share/nginx/html:z
    ports: 
      - 80:80
    links:
      - apiserver
    depends_on:
      - apiserver
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "proxy"
networks:
  board:
    external: false
