# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: Board API
  description: These APIs provide services for manipulating Board project.
  version: "0.1.0"
# the domain of the service
host: 10.110.18.37
# array of all schemes that your API supports
schemes:
  - http
basePath: /api
produces:
  - application/json
  - text/plain
consumes:
  - text/plain
  - application/json
paths:
  /users:
    get:
      summary: Get registered users of Board. (need discuss)
      description: |
        This endpoint is for user to search registered users, support for filtering results with username. Notice, by now this operation is only for administrator.
      parameters:
        - name: username
          in: query
          type: string
          required: false
          description: Username for filtering results.
      tags:
        - Products
      responses:
        200:
          description: Searched for users of Board successfully.
          schema:
            type: array
            items:
              $ref: '#/definitions/UserDetail'
        400:
          description: Invalid user ID.
        401:
          description: User need to log in first.
        403:
          description: User does not have permission of admin role.
        500:
          description: Unexpected internal errors.
    post:
      summary: Creates a new user account.
      description: |
        This endpoint is to create a user if the user does not already exist.
      parameters:
        - name: user
          in: body
          description: New created user.
          required: true
          schema:
            $ref: '#/definitions/UserDetail'
      tags:
        - Products
      responses:
        201:
          description: User created successfully.
        400:
          description: Unsatisfied with constraints of the user creation.
        403:
          description: User registration can only be used by admin role user when self-registration is off.
        500:
          description: Unexpected internal errors.
  /users/info:
    get:
      summary: Get current user info.
      description: |
        This endpoint is to get the current user infomation.
      tags:
        - Products
      responses:
        200:
          description: Get current user information successfully.
          in: body
          schema:
            $ref: '#/definitions/UserDetail'
        401:
          description: User need to log in first.
  /users/{user_id}:
    put:
      summary: Update a registered user to change his profile.
      description: |
       This endpoint let a registered user change his profile.
      parameters:
        - name: user_id
          in: path
          type: integer
          format: int
          required: true
          description: Registered user ID
        - name: user_profile
          in: body
          description: Only email, realname and comment can be modified.
          required: true
          schema:
            $ref: '#/definitions/UserProfileUpdate' 
      tags:
        - Products
      responses:
        200:
          description: Updated user's admin role successfully.
        400:
          description: Invalid user ID.
        401:
          description: User need to log in first.
        403:
          description: User does not have permission of admin role.
        404:
          description: User ID does not exist.
        500:
          description: Unexpected internal errors.
    delete:
      summary: Mark a registered user as be removed.
      description: |
        This endpoint let administrator of Board mark a registered user as
        be removed.It actually won't be deleted from DB.
      parameters:
        - name: user_id
          in: path
          type: integer
          format: int
          required: true
          description: User ID for marking as to be removed.
      tags:
        - Products
      responses:
        200:
          description: Marked user as be removed successfully.
        400:
          description: Invalid user ID.
        401:
          description: User need to log in first.
        403:
          description: User does not have permission of admin role.
        404:
          description: User ID does not exist.
        500:
          description: Unexpected internal errors.
  /users/{user_id}/adminrole:
    put:
      summary: Update a registered user to change to be an administrator of Harbor.
      description: |
        This endpoint let a registered user change to be an administrator
        of Harbor.
      parameters:
        - name: user_id
          in: path
          type: integer
          format: int
          required: true
          description: Registered user ID
        - name: user_admin_role
          in: body
          description:  Toggle a user to admin or not.
          required: true
          schema:
            $ref: '#/definitions/UserAdminRoleUpdate'
      tags:
        - Products
      responses:
        200:
          description: Updated user's admin role successfully.
        400:
          description: Invalid user ID.
        401:
          description: User need to log in first.
        403:
          description: User does not have permission of admin role.
        404:
          description: User ID does not exist.
        500:
          description: Unexpected internal errors.
  /users/{user_id}/password:
    put:
      summary: Change the password on a user that already exists.
      description: |
        This endpoint is for user to update password. Users with the admin role can change any user's password. Guest users can change only their own password.
      parameters:
        - name: user_id
          in: path
          type: integer
          format: int
          required: true
          description: Registered user ID.
        - name: user_password
          in: body
          description: Password to be updated.
          required: true
          schema:
            $ref: '#/definitions/UserPasswordUpdate'          
      tags:
        - Products
      responses:
        200:
          description: Updated password successfully.
        400:
          description: Invalid user ID; Old password is blank; New password is blank.
        401:
          description: Don't have authority to change password. Please check login status.
        403:
          description: Old password is not correct.
        500:
          description: Unexpected internal errors.
definitions:
  UserDetail:
    type: object
    properties:
      user_id:
        type: integer
        format: int
        description: The ID of the user.
      user_name:
        type: string
      user_email:
        type: string
      user_password:
        type: string
      user_realname:
        type: string
      user_comment:
        type: string
      user_deleted:
        type: integer
        format: int32
      user_isadmin:
        type: integer
        format: int
      user_reset_uuid:
        type: string
      user_salt:
        type: string
      user_creation_time:
        type: string
      user_update_time:
        type: string
  UserPasswordUpdate:
    type: object
    properties:
      user_password_old:
        type: string
        description: The user's existing password.
      user_password_new:
        type: string
        description: New password for marking as to be updated.
  UserProfileUpdate:
    type: object
    properties:
      user_email:
        type: string
        description: The new email.
      user_realname:
        type: string
        description: The new realname.
      user_comment:
        type: string
        description: The new comment.
  UserAdminRoleUpdate:
    type: object
    properties:
      user_admin_role: 
        type: integer
        description: 1-has admin, 0-not.